name: Build

on:
    push:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        name: PHPUnit Tests
        strategy:
            fail-fast: false
            matrix:
                php: [ '8.1', '8.2' ]
                symfony: [ '6.3' ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    ini-values: zend.exception_ignore_args=false
                    tools: flex

            -   name: Get composer cache directory
                id: composerCache
                run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            -   name: Cache dependencies
                uses: actions/cache@v3
                with:
                    path: ${{ steps.composerCache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                    restore-keys: ${{ runner.os }}-composer-

            -   name: Install dependencies
                run: |
                    export SYMFONY_REQUIRE=${{ matrix.symfony }}
                    composer global config --no-plugins allow-plugins.symfony/flex true
                    composer global require --no-progress --no-scripts --no-plugins symfony/flex
                    composer update --prefer-dist --no-progress
            
            -   name: Run tests
                run: vendor/bin/phpunit --coverage-text